name: variational_bayes
channels:
  - conda-forge
dependencies:
  - python
  - pytest
  - pytest-cov
  - numpy
  - scipy
  - matplotlib
  - pandas
  - jupyter
  - pylint
  - requests
  - cython
  - networkx
  - pip:
    - tqdm
    - mechanicalsoup
